public class WSUtilsV2 {
    public class WSV2 {
		public String TransactionId;
        public String TransactionDate;
        public String FormType;
        public String Salutation;
        public String FirstName;
        public String LastName;
        public String CompanyName;
        public String AddressLine1;
        public String AddressLine2;
        public String AddressLine3;
        public String AddressLine4;
        public String AddressLine5;
        public String Zip;
        public String City;
        public String Region;
        public String Country;
        public String Email;
        public String Phone;
        public String PhoneArea;
        public String AddressType;
        public String Message;
        public String Newsletter;
        public String FacerId;
        public String FacerLocationId;
        public String CampaignId;
        public String DonationId;
        public String Amount;
        public String CurrencyAmount;
        public String ReferenceId;
        public String CustomerId;
        public String DonationType;
        public String Preference;
        public String Frequency;
        public String PaymentType;
        public String CreditCardHolder;
        public String CreditCardNumber;
        public String CreditCardExpiry;
        public String CreditCardType;        
        public String PaymentStatus;    
 	}
}